### ISSUE TITLE
Status wird nicht richtig dargestellt

### ISSUE THREAD

**Issue by raz3r-code** [raz3r-code/sfdl-bash-loader#12]
Statuszeile wiederholt sich nach dem Start
-> Soll durch neue Zeile ersetzt werden

**Comment by JobbeDeluxe** [comment]
Was genau ist damit gemeint?
Ich kenne nur das Symptom das der Status nach ein paar Zeilen einfach 2 Zeilen nutzt weil die voraussichtliche Zeit zu lang wird

**Comment by raz3r-code** [comment]
Genau das Symptom. Habe es nur auf Mac getestet kann deshalb auch daran liegen. Wollte ich nochmal nachgehen

**Comment by JobbeDeluxe** [comment]
Das liegt an der Anzahl der Zeichen. Nervt mich auch etwas. Unter Linux ist es auch so. Ab 10 Prozent tritt es eigentlich auf.
Müssen wir eventuell mal gucken

**Comment by JobbeDeluxe** [comment]
added fix zum pullen, guck mal ob dir das gefällt. damit ist das auf jedenfall nicht mehr zu lang.

**Comment by raz3r-code** [comment]
Können wir so machen. Nur bitte in die richtige Datei :)

**Comment by JobbeDeluxe** [comment]
neuer Pull #17

**Comment by raz3r-code** [comment]
gefixxt mit #17
