### ISSUE TITLE
Speedreport Zeit ist Gesamtzeit

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#13]
Nach Jedem Download wird sowas hingeschrieben:
 Speedreport: Downloaded: 23 Dateien (955M), in 05:27:49 (.048 MB/s | .388 Mbit/s) 
Die "in Zeit" ist aber die Zeit seid der Loader läuft, stimmt daher nur beim ersten Download, alle nachfolgenden sind falsch.

**Comment by raz3r-code** [comment]
Ist mir noch nicht aufgefallen, schaue ich mal nach in meinen letzten Speedreports.

**Comment by JobbeDeluxe** [comment]
Das ist nur wenn mehrere Daten gleichzeitig beim ersten Starten drin sind. Getestet mit aktueller Version

**Comment by raz3r-code** [comment]
Habe das Problem gefixxt. Hatte die Zeit vom vorherigen Download noch als Resume drin.
Habe das einlesen vom Resume jetzt weiter nach oben geschoben und es gab noch einen kleinen Fehler in der Speedreport Berechnung.
