### ISSUE TITLE
TMDB Mod ohne Funktion

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#2]
TMDB.org: Aus down.mkv wird  ().mkv

Das ist bei allen Filmen.
Auch die Poster sind leer.
Auzug NFO:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
	<title></title>
	<originaltitle></originaltitle>
	<sorttitle> 1</sorttitle^>
	<year></year>
	<runtime></runtime>
	<outline></outline>
	<plot></plot>
	<country></country>
	<studio></studio>
	<filenameandpath>/ ().mkv</filenameandpath>
	<playcount>0</playcount>
	<lastplayed></lastplayed>
	<id>tt2250912</id>
	<tmdbid></tmdbid>
	<rlsname>[*Zensiert*]</rlsname>
	<set></set>
	<thumb aspect="poster" preview="/ ()-poster.jpg">/ ()-poster.jpg</thumb>
	<fanart>
		<thumb preview="/ ()-fanart.jpg">/ ()-fanart.jpg</thumb>
	</fanart>
	<director></director>
	<trailer>plugin://plugin.video.youtube/?action=play_video&amp;videoid=</trailer>
	<dateadded>2018-01-13 17:43:40</dateadded>
</movie>
```

Damit ist Die Funktion nicht gegeben.

**Comment by raz3r-code** [comment]
OK kann ich mir mal ansehen. Nutze selber die Funktion nicht, ist noch vom Grafsauger.

**Comment by JobbeDeluxe** [comment]
Ich finde die Funktion bei Filmen super! Dann spart man sich das umbenennen. Aber wie genau das geht weiß ich nicht. Deswegen die Meldung hier damit das nicht vergessen wird

**Comment by JobbeDeluxe** [comment]
kann es sein das der API Key zu alt ist? habe einen Gefunden von 11.2017:
ecbc86c92da237cb9faff6d3ddc4be6d
habe noch nicht getestet.
Quelle ist aus dem  Episodiac  threat von grafus

**Comment by JobbeDeluxe** [comment]
Getestet, geht!!!
super! fix wird gepullt
