### ISSUE TITLE
Update Routine für den Updater und Config 

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#23]
Dies ist zwar jetzt kein Problem, sollte aber beachtet werden. Da sich das Update script ja auch bugfixes unterziehen kann.... Zb #22 ....

**Comment by JobbeDeluxe** [comment]
Die Update.sh updatet auch nicht die Loader.cfg. Da sollten wir uns auch was überlegen, da sich in der loader .cfg ja doch öffter mal was ändert.

Aktuell wird man auch nicht nach den Updates Gefragt, es wird einfach gemacht, da in der alten laoder config die abfrage fehlt.....

**Comment by raz3r-code** [comment]
Man könne das Update Script auch in der start.sh hole bevor man das update startet.
Die loader.cfg ist so eine sache .. dazu sollte man per script vergleichen und ggf. das fehlende einsetzen.

**Comment by raz3r-code** [comment]
Wäre glaube ich die beste lösung

**Comment by JobbeDeluxe** [comment]
zumindest die Zeilen anzahl vergleichen. das sollten wir jedenfalls weiter testen.
Das Update script muss es eventuell 2 mal geben, damit es irgendwie eins nach dem anderen machen kann, bin mir aber nicht sicher wie das gehen soll. Noch nicht

**Comment by raz3r-code** [comment]
ich habe mal eine mögliche lösung erstellt ec4c8303d3b5663243fc09ff2795708dcf12528c
ist noch ungetestet

**Comment by JobbeDeluxe** [comment]
#34 wäre eine gute lösung für den Updater. Habe ich getestet.
