### ISSUE TITLE
Updater Frage reagiert nur auf "j"

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#25]
Bei der frage wird nur nach "j" geguckt, sinvoll wäre Hier J,j, ja. Auch ist es egal was man sonnst macht, er bricht immer ab. Es sollte mehr gefragt werden. ob man sich sicher ist bei eingaben die nicht j oder n sind.
Ich hab da was...... werde ich mal nachher rein schreiben

**Comment by raz3r-code** [comment]
Ok. So ist die behandlung natürlich besser. j/n hätte aber auch ausgereicht.
