### ISSUE TITLE
Fehler bei der Versionserkennung und Start des Loaders nach Update

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#28]
Install in der Readme
"wget https://raw.githubusercontent.com/raz3r-code/sfdl-bash-loader/master/sfdl_bash_loader/update.sh -v -O update.sh && ./update.sh install; rm -rf update.sh"

Endet in einem "bash: ./update.sh: Keine Berechtigung"

**Comment by JobbeDeluxe** [comment]
Danach wird immer ein Fehler ausgegeben:
"cat: ./sys/logs/version.txt: Datei oder Verzeichnis nicht gefunden"

ursache ist das:
"version_local=$(cat "./sys/logs/version.txt" | cut -d"." -f2)"
Nach dem install ist aber das script nicht in dem Ordner. dadurch wird immer falsch berechnet.

**Comment by JobbeDeluxe** [comment]
vielleicht mit dem fix #24 ?

Werde ich nach den ganzen maregd mal testen.

**Comment by raz3r-code** [comment]
Damit hat er immer eine Version. Sollte aber auch immer vorhanden sein (evtl. mal Log gelöscht?).

**Comment by JobbeDeluxe** [comment]
Bei einem install ist er aber in einem anderen Ordner. Da geht der Code nicht. Da du von dem Script aus denkst. Aber beim install ist das Script wo anders.

**Comment by raz3r-code** [comment]
Bei dem Install sollte er die alte Version ignorieren. Habe ich das nicht abgefangen ?

**Comment by JobbeDeluxe** [comment]
Beim install schon. Aber er starter nachher den loader. Und da ist das Problem. Die start.sh geht nicht von sich selbst aus sonder von dem order wo das install script war. Reproduzieren lässt sich das zb wenn du den bash loader von einem Verzeichnis vorher startest. Das geht auch nicht

**Comment by raz3r-code** [comment]
Ah ok. Jetzt weiß ich was du meinst. Ich hatte erst das starten nicht eingebaut. war nen quickie

**Comment by raz3r-code** [comment]
Evtl. findest du ja eine lösung. Noch ist ja alles im beta status und noch nicht voll durchgetestet

**Comment by raz3r-code** [comment]
mit #30 ignoriert er das update wenn keine version gefunden wird. diese wird ja nacht dem ersten ausfühen erstellt oder kommt mir dem update

**Comment by JobbeDeluxe** [comment]
#30 getestet. OK
