### ISSUE TITLE
Downloadzeit resetet sich nach Pause

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#33]
Jetzt ist die Download zeit immer auf 0 wenn er einen Download weiter macht.
Dadurch wird die Downloadzeit im speedreport auch verfälscht. So wie der download speed.
Er scheint bei resume die download zeit nicht richtig einzulesen.

**Comment by raz3r-code** [comment]
Muss ich mir noch einmal anschauen.

**Comment by raz3r-code** [comment]
Die Log datei darf nicht gelöscht werden. Erst nach ende des Downloads. 
Ich habe die berechnung auch noch einmal überarbeitet, somit sieht man auch im Debug Mode was vor sich geht.
