### ISSUE TITLE
Update Routine für die Config

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#36]
Die Config muss noch Überprüft werden.
wurde mit dem anderen geschlossen. #23

**Comment by raz3r-code** [comment]
Ja ich denke da an cmp oder diff da es schon in vielen distros enthalten ist

**Comment by JobbeDeluxe** [comment]
also mit diff und patch datei habe ich gute ergebnisse erreicht. Ich guck mal ob mann da noch was machen kann. Die lesbarkeit ist gut. Jetzt muss ich nur noch rausfinden wie ich neue Zeilen filtern kann.

**Comment by raz3r-code** [comment]
Wichtig wäre auch noch die neue Zeile "einzuschieben" und nicht einfach anzuhängen.

**Comment by JobbeDeluxe** [comment]
Das wäre mit patch möglich, nur kann ich bis jetzt nur alle Änderung machen, das wäre aber schlecht, da dann die Einstellungen verloren gehen. Ich teste noch

**Comment by raz3r-code** [comment]
Ich habe mal ein wenig mit diff und patch rumgespielt.
Durch eine Diff Datei die bearbeitet wird ist das Patchen möglich.
Muss nurnoch die Diff Datei vernünftig bearbeitet bekommen.

**Comment by JobbeDeluxe** [comment]
ja, da steh ich auch grad dafür, mann muss jede zeile die mit - anfängt und mit + folgt entfernen und welche die "nur" mit + anfangen lassen. Das hab ich aber auch noch nicht ganz geschafft.

**Comment by raz3r-code** [comment]
Ich kann diese mittlerweile entfernen .. nur muss dann aber auch von dem @@ bis zum nächsten @@ alles entfernt werden damit die Diff datei konsistent bleibt.

**Comment by raz3r-code** [comment]
`		#--------------------------------------
		# Überprüfe Config auf änderung
		#--------------------------------------

		#hole diff und zeilen zum löschen
		diff -u "$pwd/backup/loader.cfg" "$pwd/sys/loader.cfg" > "$pwd/backup/loadercfg.diff"
		grep -E "^\-" "$pwd/backup/loadercfg.diff" > "$pwd/backup/del_lines.diff"

		while IFS='' read -r line || [[ -n "$line" ]]; do

			conf_var=$(echo ${line:1} |cut -d"=" -f1)
			add_found=$(grep "+$conf_var" "$pwd/backup/loadercfg.diff")

			if ! [ -z "$add_found" ]; then
				sed -i "/$conf_var/d" "$pwd/backup/loadercfg.diff"
			fi

		done < "$pwd/backup/del_lines.diff"`

**Comment by raz3r-code** [comment]
Kannst du dir ja mal anschauen

**Comment by JobbeDeluxe** [comment]
Guck ich mir nachher mal an.
Ich bin jetzt so weit dass ich theoretisch alle neuen Zeilen in eine Datei sauber schreiben kann. Danach einfach an die original config unten dann hängen kann. Funktioniert super.
Und beim letzten test hat diff auch die unsortierten Zeilen super erkannt. 
Ich zeige es dir nachher mal.

**Comment by JobbeDeluxe** [comment]
```
echo -e "\n" >>loader_bak.cfg
diff -y loader_bak.cfg loader.cfg | grep ">" | cut -d" " -f7 | tr -d '>' | sed 's/^[ \t]*//' >diffloader.diff
cat diffloader.diff >>loader_bak.cfg
sed -e '/^ *$/d' loader_bak.cfg > loader_new.cfg
```

Das ist meine Idee, damit sind die Neuen Zeilen aber immer Unten.
beim nächsten diff würde das aber vielleicht probleme machen. Mann müsste jetzt ein schnitt machen. zB. Version 4. Dabei die config zwingend auf den neuen stand bringen und dem User sagen das seine config neu machen muss.
Dann kann man alle änderungen immer unten an die loader.cfg anhängen, dann würde das ohne probleme weiterhin funktionieren.

Edit:
Ich habe versucht dein Code mal so zu lesen, da du ja schon mit den echten variablen hantierst. Leider scheint das nicht so ganz zu funktionieren. Bei mir makiert er immer die letzte zeile. Ich konnte mich da nicht so schnell in die zeilen reindenken um das in eine sandbox zu schmeissen.
Ich muss das wohl mal in der Natur testen. Ab damit in die Updater datei und dann teste ich das mal. gucken wir morgen mal

EDIT2:
Habe dein script geht irgendwie garnicht bei mir. hat nichts gefiunden was fehlt

**Comment by raz3r-code** [comment]
Ich schaue nochmal drüber. Dabei geht es ja nur um das Prinzip.
1. hole mir die Diff 
2. schaue welche sollen gelöscht / bearbeitet werden
3. gucke in den die bearbeitet werden sollen ob diese zweimal existieren zum wieder hinzufügen
4. wenn sie zweimal existieren diese aus der diff datei löschen 
5. patch anwenden 

Dabei hakt es aber noch bei 4. da ich wie gesagt von @@ zum nächsten @@ alles löschen muss um die diff konsistent zu halten.

**Comment by raz3r-code** [comment]
deine lösung würde funktionieren wäre für mich aber nur ein notnagel. 
Wie gesagt: Mir fehlt nur noch eine elegante Lösung um die diff ordentlich zu bearbeiten.

**Comment by JobbeDeluxe** [comment]
Ich glaube du hast da ein Denkfehler? Du sortiert die entfernt Zeilen. Aber sollten nicht die plus Zeilen das sein was wir brauchen?
Aber vielleicht hilft dir eine andere Anzeige? Zum Beispiel diff - y? Dabei wird die Ausgabe anders dargestellt.
Ich teste nochmal ein bisschen mit deiner Ausgabe. Vielleicht kann ich dir bei dem Problem helfen.

**Comment by raz3r-code** [comment]
Ob ich nun nach + oder - suche ist eigentlich egal .. da das nur zum nachschlagen von dopplungen ist.
Erst bei einer Dopplung soll gelöscht werden.
Ich probiere grade aber auch noch einen anderen Ansatz aus.

**Comment by raz3r-code** [comment]
Habe eine Lösung für die Config #41

**Comment by JobbeDeluxe** [comment]
Funktioniert bei mir garnicht.
er findet die änderungen in der config nicht. Und gibt zum teil eine menge fehler ab:
```
# =======================================================================================================
# SFDL BASH-Loader - Installer/Updater - raz3r - Version 1.0
# =======================================================================================================
| system: Linux
| -------------------------------------- 
| Alle Pakete installiert!
| Starte Installation in 5 Sekunden ...
| -------------------------------------- 
| Installiert Version: 3.11
| Aktuelle Version:    3.14
| -------------------------------------- 
| ! Neue Version wird installiert !
| -------------------------------------- 
| Konfiguration speichern...
| Download wird gestartet.
| Bitte warten ...
| Konfiguration wiederherstellen...
/home/User/sfdl_bash_loader/update.sh: Zeile 161: [: Zu viele Argumente.
/home/User/sfdl_bash_loader/update.sh: Zeile 161: [: 10:35c37,43: Zweistelliger (binärer) Operator erwartet.
/home/User/sfdl_bash_loader/update.sh: Zeile 161: [: 9:35c37,43: Zweistelliger (binärer) Operator erwartet.
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
sed: -e Ausdruck #1, Zeichen 3: Unerwartetes `,'
| Update abgeschlossen 
| -------------------------------------- 
| Starte BASH-Loader in 5 Sekunden ...
/home/User/sfdl_bash_loader/update.sh: Zeile 202: /home/User/sfdl_bash_loader/start.sh: Keine Berechtigung
/home/User/sfdl_bash_loader/update.sh: Zeile 202: exec: /home/User/sfdl_bash_loader/start.sh: Kann nicht ausführen: Keine Berechtigung

```

**Comment by JobbeDeluxe** [comment]
Habe das noch mal blanko getestet, er startet zu mindestens, aber die loader.cfg hat immer noch keine zusätzliche zeilen von dem was ich entfernt habe.

Es ist nicht wirklich greifbar:
er kann bei 80 der fälle nicht die start.sh starten.
Im Userscript ordner ist noch ein userscript ordner und der Backupordner wird nicht entfernt.
Das ist alles irgendwie noch nicht sicher.
2 mal von den 30 bis 40 versuchen die ich gemacht habe hat vielleicht geklappt, da kann ich aber vielleicht auch die alte update.sh genutz haben ;)

**Comment by raz3r-code** [comment]
ok ich schaue nochmal .. bei mir sind die tests positiv gewesen. Teste auch nochmal mit nem frischem System.

**Comment by raz3r-code** [comment]
War mist .. ich habe noch mehr fehler gefunden.. denke aber das ich das heute trotzdem hin bekommen werde

**Comment by raz3r-code** [comment]
be01efd1b1e656249d360e050043e5fa0ce8bc0a

**Comment by raz3r-code** [comment]
Bitte einmal testen :)

**Comment by JobbeDeluxe** [comment]
| Konfiguration wiederherstellen...
patch: **** unexpected end of file in patch at line 3
| Update abgeschlossen 
loader.cfg ist immernoch auf dem stand von 3.9.1
Geht nicht. Mehrfach versucht.

**Comment by raz3r-code** [comment]
OK. Mit so vielen Änderungen habe ich das Script nicht getestet. Dabei Hast du recht .. er packt nämlich auch Hinzugefügtes mit in "Changed", das ist ein Problem.

**Comment by JobbeDeluxe** [comment]
ich habe einfach die Datei genommen die auf der Hompage noch verfügbar ist, da ich dachte das ist eine die durchaus viele noch nutzen.
eine Ausnahme ist mir noch aufgefallen.
tmdb_api_key=
Der muss auf jedenfall upgedatet werden.
[backup.zip](https://github.com/raz3r-code/sfdl-bash-loader/files/1818551/backup.zip)
anbei noch mal die ganzen backup files.
Basis war eine 3.8.3. Hatte nur die cfg in debug gesetzt und ein retry auf 1 gesetzt, mehr nicht.

**Comment by JobbeDeluxe** [comment]
ich habe es jetzt geschafft jede config die ich hier rumfliegen habe upzudaten:
Das ist der "update" Vorgang. muss noch in den prozess selber eingepflegt werden:
`#!/bin/bash
pwd='$pwd'
ppwd='$pwd/..'
source ./loader.cfg.new
source ./loader.cfg.bak

echo -e "debug=$debug						# debug true/false 
sfdl_logo=$sfdl_logo						# ascii logo true/false
sfdl_color_text=$sfdl_color_text					# text mit farbe true/false
sfdl_entferne_logs=$sfdl_entferne_logs					# wget download-logs entfernen true/false
sfdl_fortsetzen=$sfdl_fortsetzen					# ask = fragen, true = immer fortsetzen, false = immer neu laden
sfdl_wget_download=$sfdl_wget_download					# true = wird mit wget laden, false = wird wget download ignorieren
sfdl_wget_max_retry=$sfdl_wget_max_retry					# maximale anzahl an versuchen eine datei zu laden 0 = unbegrenzt
sfdl_wget_max_retry_index=$sfdl_wget_max_retry_index				# versuche fuer index laden
sfdl_rar_auspacken=$sfdl_rar_auspacken					# rar archive auspacken true/false
sfdl_rar_entfernen=$sfdl_rar_entfernen					# rar archive nach dem auspacken entfernen true/false
sfdl_xrel_tmdb_mod=$sfdl_xrel_tmdb_mod					# lade daten von xrel.to und tmdb.org true/false
sfdl_wget_multithread=$sfdl_wget_multithread				# true = es werden gleichzeitig mehrere dateien geladen
sfdl_wget_multithreads=$sfdl_wget_multithreads				# sfdl = MaxDownloadThreads, sfdl_wget_multithreads=10 z.B. ueberschreibt die vorgabe durch MaxDownloadThreads und oeffnet 10 gleichzeitige verbindungen
sfdl_eigenwerbung=$sfdl_eigenwerbung					# schreibt werbung in den speedreport
sfdl_chmod=$sfdl_chmod						# Rechte verteilung der Daten nach und während dem download/ nach dem Entpacken
sfdl_update=$sfdl_update						# ask = fragen, true = immer updaten, false = nicht updaten
#==========================================================================================================
uscript_folder=\"$uscript_folder\"   			#absoluter Pfad zu script Ordner
uscript_befor=$uscript_befor               			#Userscript vor dem Download ausführen. true zum aktivieren
uscript_after=$uscript_after               			#Userscript nach dem Download ausführen. true zum aktivieren
uscript_end=$uscript_end               				#Userscript nach dem kompletten Download ausführen. true zum aktivieren
#==========================================================================================================
#Proxy Einstellungen
proxy=$proxy                     			#true zum proxy aktivieren 
proxyauth=$proxyauth                   			#true wenn proxy Username oder password erforderlich. ansonsten werden die user und pass ignoriert
proxytyp=$proxytyp                     			#http ACHTUNG: lftp unterstützt nur HTTP!!
proxyuser=$proxyuser                        			#wenn erforderlich
proxypass=$proxypass                        			#wenn erforderlich
proxyip=$proxyip                         	 		#ip angabe wenn aktiviert
proxyport=$proxyport                        			#proxy Port
#==========================================================================================================
sfdl_files=\"$sfdl_files\"				# pfad wo sfdl files gesucht werden
sfdl_logs=\"$sfdl_logs\"					# wget download logs
sfdl_downloads=\"$sfdl_downloads\"			# pfad wo downloads gespeichert werden
sfdl_sys=\"$sfdl_sys\"						# pfad fuer wichtige tools
sfdl_status=\"$sfdl_status\"				# pfad zur status dir
#==========================================================================================================
# unrar: alternative versionen falls systemweit kein unrar installiert ist (nur fuer den notfall gedacht!), besser: apt-get install unrar
# sfdl_unrar="'"$sfdl_sys/unrar-3.4-openbsd/unrar"'"
# sfdl_unrar="'"$sfdl_sys/unrar-3.7.7-centos/unrar"'"
# sfdl_unrar="'"$sfdl_sys/unrar-4.1.3-armv4l/unrar"'"
# sfdl_unrar="'"$sfdl_sys/unrar-5.3.7-arm/unrar"'"
sfdl_unrar=\"$sfdl_unrar\"
# ========================================================================================================
tmdb_api_key=\"$tmdb_api_key\" 	# kodi api key: $tmdb_api_key
tmdb_language=\"$tmdb_language\"					# de = informationen zum film sind immer deutsch
# wird in die kodi.nfo eingetragen und kodi wird hier nach dem film suchen
# alternativen z.b. \"smb://user:pass@127.0.0.1/filme\" oder ein lokaler pfad wie \"/home/kodi/filme\"
kodi_pfad_zum_film=\"$kodi_pfad_zum_film\" 		# kein / am ende
kodi_pfad_zum_cover=\"$kodi_pfad_zum_cover\"		# oder z.b. \"http://127.0.0.1/cover\" kein / am ende
kodi_pfad_zum_hintergrund=\"$kodi_pfad_zum_hintergrund\"	# kein / am ende
kodi_pfad_zum_actor=\"$kodi_pfad_zum_actor\"		# kein / am ende
# ========================================================================================================
sfdl_status_webserver=$sfdl_status_webserver				# schaltet webserver an oder aus; true = ein | false = aus
sfld_status_webserver_port=$sfld_status_webserver_port				# legt den port fest, unter dem der webserver errreichbar ist
sfdl_status_json_file=\"$sfdl_status_json_file\"		# json status datei
sfdl_status_start_passwort=\"$sfdl_status_start_passwort\"			# legt das passwort fuer den bash loader remote start fest (UNBEDINGT AENDERN!!!)
sfdl_status_stop_passwort=\"$sfdl_status_stop_passwort\"				# legt das passwort zum beenden des laufnden bash loaders fest (UNBEDINGT AENDERN!!!)
sfdl_status_kill_passwort=\"$sfdl_status_kill_passwort\"			# legt das passwort zum remote beenden des webservers fest (UNBEDINGT AENDERN!!!)
sfdl_status_timout=$sfdl_status_timout					# webserver timout
sfdl_status_php_ini_path=\"$sfdl_status_php_ini_path\"				# pfad in der die php.ini abgelegt ist
sfdl_status_doc_root=\"$sfdl_status_doc_root\"			# doc root - pfad zu den html/php usw files" >./loader.cfg`

**Comment by JobbeDeluxe** [comment]
Guck dir das mal an:

damit konnte ich bis jetzt jede cfg upzudaten ohne probleme:
https://github.com/raz3r-code/sfdl-bash-loader/blob/JobbeDeluxe-cfg-update/sfdl_bash_loader/updatecfg.sh

**Comment by raz3r-code** [comment]
Scheint zu funktionieren. Ist nur ein ziemlich großer Aufwand das ganze zu pflegen.
Der Ansatz mit sed -c -i "s/\($CFG_KEY *= *\).*/\1$CFG_VALUE/" sys/loader.cfg
funktioniert, dort gibt es nur Probleme mit Kommentaren und Pfaden :(

**Comment by JobbeDeluxe** [comment]
Ja hab ich auch festgestellt. Aber besser ein bisschen pflegeaufwand als garnicht zu funktionieren. Das mit dem ersetzen hab ich auch schon versucht. Es zerstört die ganze Formatierung. Deswegen ist meine Idee eigentlich sehr gut. Es muss ja nur wenn neue Variablen dazu kommen editiert werden.

**Comment by JobbeDeluxe** [comment]
Was mir noch mal aufgefallen ist:
Der IMDB Key muss nicht als variable da stehen sonder muss immer fest eingetragen werden. Denn das ist eigentlich keine "einstellung" sonder ein fester wert der so bleiben muss.

**Comment by raz3r-code** [comment]
Der ändert sich ab und an doch einmal und wenn jemand einen eigenen Key einpflegen will kann er dies auch tun. Deshalb ist dieser in den Einstellungen

**Comment by JobbeDeluxe** [comment]
Ok, dann muss dieser aber extra in einer update Routine wiederfinden. Denn wenn er mal erneuert werden muss bleibt er jetzt immer so wie er ist. Das wäre schlecht. Daher muss der bei bestimmten Werten neu gezwungen werden.

**Comment by raz3r-code** [comment]
wir können ja noch eine update datei für neue werte mitgeben die wie die config aussieht.. 
beudeute: 
-> lese neue config
-> überschreibe mit werten aus der alten config 
-> überschreibe mit werten aus der force.conf

**Comment by JobbeDeluxe** [comment]
Gefällt mir.

**Comment by raz3r-code** [comment]
Habe ich grade mal bei dir "eingebaut".
Sollten die Updatecfg.sh mit parametern starten.
D.h. eingabe wären die alte, neue config sowie die force datei und wo die neue cfg gespeichert werden soll. Somit kann die updatecfg.sh mit in das sys verzeichniss und wird immer mit geupdatet.
Willst du das fertig machen ?

**Comment by JobbeDeluxe** [comment]
Ich setz mich da gerne morgen mal ran.

**Comment by raz3r-code** [comment]
So habe auch noch etwas "umgebaut" .. gute Arbeit 👍 💯 🥇
