### ISSUE TITLE
Zertifikat ignorieren und SSL aus?

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#44]
Ich habe grad mich ein bisschen mit lftp und zertifikaten beschäfftigt,
dabei ist mir aufgefallen das wir einmal zertifikate ignorieren UND danach unverschlüsselt verbinden.
Das ist glaube ich unnötig. Wenn wir "set ssl:verify-certificate no;" setzen ist "set ftp:ssl-allow no;" doch eigentlich überflüssig oder?

**Comment by raz3r-code** [comment]
Naja .. ich kann mich auch verschlüsselt verbinden aber jedes Zertifikat akzeptieren.
Wenn "set ftp:ssl-allow no;" gesetzt ist, ist "set ssl:verify-certificate no;" überflüssig.
Kann aber auch sein das lftp beides benötigt. Muss man mal kurz durchtesten. Ist nur ein "schönheitsfehler"

**Comment by JobbeDeluxe** [comment]
ja, das marg sein, ich war mir auch nicht sicher ob wirklich beides gebraucht wird und das netz ist sich da auch nicht einig :D sollten wir wiklich mal testen. wenn ssl verfügbar ist sollte man es schon nutzen finde ich.
Oder noch ein ssl in die config einbauen, aber ich glaube das würde nur die config überladen.
so lange es läuft ist es erstmal zweitrangig ;)
