### ISSUE TITLE
Download resume ohne index download?

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#45]
mir ist aufgefallen das bei jeden "resume" von downloads, der Index wieder neu geladen wird. Dies sollte man vielleicht unterbinden indem man vorher abfragt ob es ein index gibt und das es nicht leer ist?

**Comment by raz3r-code** [comment]
Ich würde das so beibehalten. Man weiß nie ob ein Upper mal eine Datei nachschiebt, so wird diese auch mit geladen.

**Comment by JobbeDeluxe** [comment]
Hmmm, ok wenn das gebraucht wird kann das gerne so bleiben ;)
