### ISSUE TITLE
Sfdl ist verschlüsselt und Host ist keine IP

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#47]
Ich habe das Problem gehabt das bei der Prüfung nach dem Password die Host Variable auf eine IP geprüft wird. Jetzt gibt es aber einige die dort ein Domain namen eintragen, dadurch schlägt die entschlüssel Prüfung fehl.
Da müssen wir uns was überlegen.

**Comment by JobbeDeluxe** [comment]
Habe mal ein Decode test gemacht. https://github.com/raz3r-code/sfdl-bash-loader/tree/decode-test
so solte das eventuell auch Hostname auflösen

**Comment by raz3r-code** [comment]
Siehe Kommentar im Pull Request

**Comment by raz3r-code** [comment]
Habe da mal was übersichtlicheres gebaut #50
