### ISSUE TITLE
Version.txt kann nicht gelesen werden ab der 2. Datei

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#51]
Immer wenn mehrer sfdl daten hinzugefügt werden kann die datei nicht laden werden:

cat: /sfdl_bash_loader/sys/logs/version.txt: Datei oder Verzeichnis nicht gefunden

das steht immer da wo eigentlich die version sein sollte

**Comment by raz3r-code** [comment]
Konnte ich noch nicht nachstellen.

**Comment by JobbeDeluxe** [comment]
Kann ich aber bei jedem mal ;).
Einfach 2 Daten gleichzeitig laden. Schon kommt das bei der 2. Datei.

**Comment by JobbeDeluxe** [comment]
Ganz ehrlich,
konte ich nicht nachstellen ist echt nicht schön.
Ich habe wieder weil mich das nervt mal im code gelesen:
1.) die versionsdatei wird erstellt im "bashloader.sh"
2.) die Versions datei wird am ende von basloader gelöscht für "# entferne wget & lftp temp files" das heist die sind jetzt ist keine Version.txt mehr da. Aber die 2. sfdl wird gelsen.
3.) es wird keine Version.txt wieder erstellt, da das vor der *.sfdl schleife war
4.) bei jedem start einer SFDL wird die info an die prog.sh übergeben, die Fragt am anfang nach der Version.txt die es jetzt nicht mehr gibt!

Fazit:
Ganz klar das der Fehler kommt.
Das einfach hier zu schliesen finde ich FAUL
