### ISSUE TITLE
[ERWEITERUNG] Kategorien. 

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#57]
Ich würde gerne bestimmte Daten in bestimmten Download Ordner ablegen lassen, damit lässt sich der nachträgliche Aufwand minimieren

**Comment by raz3r-code** [comment]
Kannst du gene in irgendeiner Form als Userscript Addon aufbauen, würde es aber nicht in den offiziellen Build mit aufnehmen wollen.
