### ISSUE TITLE
[ERWEITERUNG] Manuelle Benennung 

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#58]
Im moment wird der download Ordner immer so angelegt wie der sfdl name ist. Ich würde mir wünschen das ich die sfdl einfach umbenennen kann und die letzte datei die Avi zb auch so genannt wird. Das ist bei weitem besser als was die datei immer Standardmäßig heißt. 
Der Name im Ordner ist unnötig, da ich ja nicht die ganzen Ordner sammeln will. Wenn doch, ok der Name ist ja schon da.

**Comment by raz3r-code** [comment]
Eine Datei umbenennen ist jetzt kein Hexenwerk im Terminal. 
Es gibt die TMDB Option. Diese benennt beides entsprechend nach erkennung um.
Ansonsten -> Userscript
