### ISSUE TITLE
Verzeichniss kann nicht geöffnet werden

### ISSUE THREAD

**Issue by JobbeDeluxe** [raz3r-code/sfdl-bash-loader#6]
find: Zugriff nicht möglich:550 No such directory. (/08.  .Â Â Â Â )
find: Zugriff nicht möglich:550 No such directory. (/Â«Â»)
find: Zugriff nicht möglich:550 No such directory. (/HDD)
find: Zugriff nicht möglich:550 No such directory. (/1Â«Â»)
find: Zugriff nicht möglich:550 No such directory. (/Â Â Â Â .Â Â Â Â Â Â `)Â .)

Das sollte es Sein:
/08.  '.      «» HDD 1«»      .'      `) .'

Da stimmt was nicht mit den Verzeichnisse namen im linux oder sfdl

**Comment by raz3r-code** [comment]
Schon kontrolliert ob überhaupt der Ordner noch da ist.
Sonst eben mir eine PN mit Link schicken. Dann schau ich mal nach.

**Comment by JobbeDeluxe** [comment]
habe doch geschrieben wie das verzeichniss unter windows angezeigt wird:
/08. '.     «» HDD 1«»     .'      `) .'
aber unter linux wird es falsch dargestellt.
und ja über ftp geht alles

**Comment by JobbeDeluxe** [comment]
ich habe getestet:
unter terminal sieht das ganze so aus:
08.\ \ \'.    \ \ «»\ HDD\ 1«»\ \     .\'      `) .\'/

**Comment by JobbeDeluxe** [comment]
Auch closed ohne fix?
